setwd("/home/max/Dropbox/FMDV_AMERICA/DATA")
raw<-data.frame(read.table("database_trade.txt",TRUE))
Locations<-c("Argentina","Brazil","Bolivia","Colombia","Ecuador","Peru","Uruguay","Venezuela")
l<-as.factor(Locations)
imp<-subset(subset(raw,FLUX=="Import"),TO==Locations)
exp<-subset(subset(raw,FLUX=="Export"),TO==Locations)
grid<-expand.grid(Locations,Locations);names(grid)<-c("FROM","TO");gridb<-grid
#########################
ex<-c(exp$FROM);ey<-c(exp$TO);ez<-c(exp$YEAR);eg<-data.frame(ex,ey,ez)
ix<-c(imp$FROM);iy<-c(imp$TO);iz<-c(imp$YEAR);ig<-data.frame(ix,iy,iz)
library(rgl)
plot3d(ex,ey,ez)
plot3d(ix,iy,iz,col=3,add=T)#apparently, no overlapping
#########################
FROM<-as.factor(c(as.character(imp$TO),as.character(exp$FROM)))
TO<-as.factor(c(as.character(imp$FROM),as.character(exp$TO)))
Cattle<-c(imp$Cattle,exp$Cattle)
Sheep<-c(imp$Sheep,exp$Sheep)
Pig<-c(imp$Pig,exp$Pig)
D<-data.frame(FROM,TO,Cattle,Sheep,Pig)
#
#Cattle=1
#Sheep=2
#Pig=3
cattle<-vector()
 for(i in 1:nrow(grid)){
  corresp<-subset(subset(D,FROM==paste(grid[i,1])),TO==paste(grid[i,2]))
   if(dim(corresp)[1]>0){
    cattle[i]<-as.numeric(colSums(corresp[,3:5][1]))
   }
   else
    cattle[i]<-0
 }
cattle
####
pig<-vector()
 for(i in 1:nrow(grid)){
  corresp<-subset(subset(D,FROM==paste(grid[i,1])),TO==paste(grid[i,2]))
   if(dim(corresp)[1]>0){
    pig[i]<-as.numeric(colSums(corresp[,3:5][3]))
   }
   else
    pig[i]<-0
 }
pig
####
sheep<-vector()
 for(i in 1:nrow(grid)){
  corresp<-subset(subset(D,FROM==paste(grid[i,1])),TO==paste(grid[i,2]))
   if(dim(corresp)[1]>0){
    sheep[i]<-as.numeric(colSums(corresp[,3:5][2]))
   }
   else
    sheep[i]<-0
 }
sheep
trade<-data.frame(cattle,sheep,pig)
tradec<-data.frame(grid,cattle,sheep,pig)
write.table(tradec,file="TRADE_56.txt",sep="\t")